### ISSUE TITLE
 Ground truth of crop-weed images

### ISSUE THREAD

**Issue by hamidehkerdegari** [inkyusa/weedNet#2]
I was looking at your dataset but could not find the ground truth for crop-weed images, they are all black. Could you please let me know how to access the annotated crop-weed image data?

**Comment by inkyusa** [comment]
Hello,
Thank you for your interests in our work and pointing out this.

The annotated files are indexed images meaning that were filled with the class IDs rather than RGB values. For example, the background is 0 and crop is 1.

For further inspection, you can visualize an annotated file (e.g., https://github.com/inkyusa/weedNet/blob/master/data/Sequoia/SequoiaRed_30/testannot/0000.png) using the following MATLAB script;

```
im=imread('./0000.png');
plantColor=[0 1 0]; %green
weedColor=[1 0 0]; %red
map=[plantColor;weedColor];
rgb=label2rgb(im,map,[0,0,0]); %label img, map, bg color
imshow(rgb);
```

<img width="735" alt="screen shot 2018-09-28 at 17 44 11" src="https://user-images.githubusercontent.com/5215050/46218940-39d22300-c346-11e8-9c19-a9ee8420b4ce.png">

Hope this help and I updated the readme file in this repo.

**Comment by inkyusa** [comment]
I expect my response had addressed your question and close this issue. If not, please re-open this.

**Comment by AfiaMisbah** [comment]
> 
> 
> Hello,
> Thank you for your interests in our work and pointing out this.
> 
> The annotated files are indexed images meaning that were filled with the class IDs rather than RGB values. For example, the background is 0 and crop is 1.
> 
> For further inspection, you can visualize an annotated file (e.g., https://github.com/inkyusa/weedNet/blob/master/data/Sequoia/SequoiaRed_30/testannot/0000.png) using the following MATLAB script;
> 
> ```
> im=imread('./0000.png');
> plantColor=[0 1 0]; %green
> weedColor=[1 0 0]; %red
> map=[plantColor;weedColor];
> rgb=label2rgb(im,map,[0,0,0]); %label img, map, bg color
> imshow(rgb);
> ```
> 
> <img alt="screen shot 2018-09-28 at 17 44 11" width="735" src="https://user-images.githubusercontent.com/5215050/46218940-39d22300-c346-11e8-9c19-a9ee8420b4ce.png">
> 
> Hope this help and I updated the readme file in this repo.

**Comment by AfiaMisbah** [comment]
> 
> 
> Hello,
> Thank you for your interests in our work and pointing out this.
> 
> The annotated files are indexed images meaning that were filled with the class IDs rather than RGB values. For example, the background is 0 and crop is 1.
> 
> For further inspection, you can visualize an annotated file (e.g., https://github.com/inkyusa/weedNet/blob/master/data/Sequoia/SequoiaRed_30/testannot/0000.png) using the following MATLAB script;
> 
> ```
> im=imread('./0000.png');
> plantColor=[0 1 0]; %green
> weedColor=[1 0 0]; %red
> map=[plantColor;weedColor];
> rgb=label2rgb(im,map,[0,0,0]); %label img, map, bg color
> imshow(rgb);
> ```
> 
> <img alt="screen shot 2018-09-28 at 17 44 11" width="735" src="https://user-images.githubusercontent.com/5215050/46218940-39d22300-c346-11e8-9c19-a9ee8420b4ce.png">
> 
> Hope this help and I updated the readme file in this repo.

**Comment by AfiaMisbah** [comment]
hello sir,
 I am  also doing my project on this, for that i require ground truth annotation for all images. In dataset it is not available. can you please send ?
